name: Python application
run-name: ${{ github.actor }} is testing HNG Fast-api 🚀

on:
  push:
    branches:
      - "feature-branch"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: echo "🐍 Python 3.10 has been set up."
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest autopep8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: echo "📦 Dependencies have been installed."
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
    - name: Auto-correct PEP 8 issues with autopep8
      run: |
        autopep8 . --recursive --in-place --aggressive --aggressive
    - run: echo "✅ PEP 8 issues have been auto-corrected."
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - run: echo "🔍 Linting with flake8 completed."
    - name: Test with pytest
      run: |
        pytest tests
    - run: echo "🧪 Testing with pytest completed."
    - run: echo "🍏 This job's status is ${{ job.status }}."